use std::collections::HashSet;

use crate::ast::*;
use crate::error::Result;
use crate::validator::topological_sort;

pub fn export_markdown(doc: &Document, target_name: &str) -> Result<String> {
    let target = doc.targets.get(target_name)
        .ok_or_else(|| {
            crate::error::IcvsError::TargetNotFound {
                target: target_name.to_string(),
            }
        })?;

    let resolved_nodes = resolve_nodes(doc, target)?;

    let mut output = String::new();

    if let Some(ref name) = doc.project_name {
        output.push_str(&format!("# InstructCanvas: {}\n\n", name));
    } else {
        output.push_str("# InstructCanvas Instructions\n\n");
    }

    if let Some(ref resolve_list) = target.resolve {
        output.push_str("## Applied Rules\n\n");
        for node_id in resolve_list {
            if let Some(node) = doc.nodes.get(node_id) {
                output.push_str(&format!("### {}\n\n", node_id));
                match node.node_type {
                    NodeType::Rule => {
                        if let Some(ref content) = node.content {
                            output.push_str(&format!("**Rule:** {}\n\n", content));
                        }
                        if let Some(ref severity) = node.severity {
                            output.push_str(&format!("**Severity:** {}\n\n", severity.as_str()));
                        }
                    }
                    NodeType::Blocklist => {
                        if let Some(ref content) = node.content {
                            output.push_str(&format!("**Forbidden:** {}\n\n", content));
                        }
                        if let Some(ref trigger) = node.trigger_on {
                            output.push_str(&format!("**Trigger:** {}\n\n", trigger.as_str()));
                        }
                    }
                    NodeType::Allowlist => {
                        if let Some(ref content) = node.content {
                            output.push_str(&format!("**Allowed:** {}\n\n", content));
                        }
                        if let Some(ref trigger) = node.trigger_on {
                            output.push_str(&format!("**Trigger:** {}\n\n", trigger.as_str()));
                        }
                    }
                    NodeType::Condition => {
                        if let Some(ref cond) = node.condition {
                            output.push_str(&format!(
                                "**If** `${}` {} \"{}\" **then** -> `{}`",
                                cond.variable, cond.operator, cond.value, cond.then_node
                            ));
                            if let Some(ref else_node) = cond.else_node {
                                output.push_str(&format!(" **else** -> `{}`", else_node));
                            }
                            output.push_str("\n\n");
                        }
                    }
                    NodeType::Action => {
                        if let Some(ref content) = node.content {
                            output.push_str(&format!("**Action:** {}\n\n", content));
                        }
                    }
                }
            }
        }
    }

    output.push_str("## Dependency Graph\n\n");
    output.push_str("```\n");
    let sorted = topological_sort(doc);
    if let Ok(order) = sorted {
        for node_id in &order {
            if resolved_nodes.contains(node_id.as_str()) {
                output.push_str(&format!("  {} -> ", node_id));
            }
        }
        if !order.is_empty() {
            output.pop();
            output.pop();
            output.pop();
        }
    }
    output.push_str("\n```\n\n");

    output.push_str("---\n");
    output.push_str(&format!("_Generated by InstructCanvas for target: `{}`_\n", target_name));
    if let Some(ref ignore_list) = target.ignore {
        if !ignore_list.is_empty() {
            output.push_str(&format!("_Ignored nodes: {}_\n", ignore_list.join(", ")));
        }
    }

    Ok(output)
}

fn resolve_nodes<'a>(doc: &'a Document, target: &'a Target) -> Result<HashSet<&'a str>> {
    let mut resolved: HashSet<&str> = HashSet::new();

    if let Some(ref resolve) = target.resolve {
        for node_id in resolve {
            if doc.nodes.contains_key(node_id) {
                resolved.insert(node_id.as_str());
            }
        }
    }

    if let Some(ref ignore) = target.ignore {
        for node_id in ignore {
            resolved.remove(node_id.as_str());
        }
    }

    Ok(resolved)
}

pub fn export_dot(doc: &Document) -> Result<String> {
    let mut output = String::new();
    output.push_str("digraph InstructCanvas {\n");
    output.push_str("  rankdir = TB;\n");
    output.push_str("  node [shape = box, style = rounded];\n\n");

    for node in doc.nodes.values() {
        let shape = match node.node_type {
            NodeType::Rule => "box",
            NodeType::Blocklist => "octagon",
            NodeType::Allowlist => "diamond",
            NodeType::Condition => "diamond",
            NodeType::Action => "box",
        };
        let color = match node.node_type {
            NodeType::Rule => "#4A90D9",
            NodeType::Blocklist => "#D94A4A",
            NodeType::Allowlist => "#4AD94A",
            NodeType::Condition => "#D9C84A",
            NodeType::Action => "#9B59B6",
        };
        let label = match &node.content {
            Some(content) => {
                let truncated = if content.len() > 40 {
                    format!("{}...", &content[..37])
                } else {
                    content.clone()
                };
                format!("{}\\n({})", node.id, truncated)
            }
            None => node.id.clone(),
        };
        output.push_str(&format!(
            "  \"{}\" [label = \"{}\", shape = {}, fillcolor = \"{}\", style = \"filled,rounded\"];\n",
            node.id, label, shape, color
        ));
    }

    output.push('\n');

    for edge in &doc.edges {
        output.push_str(&format!(
            "  \"{}\" -> \"{}\";\n",
            edge.source, edge.target
        ));
    }

    for node in doc.nodes.values() {
        if let Some(ref cond) = node.condition {
            if !cond.then_node.is_empty() {
                output.push_str(&format!(
                    "  \"{}\" -> \"{}\" [label = \"true\"];\n",
                    node.id, cond.then_node
                ));
            }
            if let Some(ref else_node) = cond.else_node {
                if !else_node.is_empty() {
                    output.push_str(&format!(
                        "  \"{}\" -> \"{}\" [label = \"false\"];\n",
                        node.id, else_node
                    ));
                }
            }
        }
    }

    output.push_str("}\n");
    Ok(output)
}

pub fn export_markdown_merge(doc: &Document) -> Result<String> {
    let order = topological_sort(doc)?;

    let mut output = String::new();

    if let Some(ref name) = doc.project_name {
        output.push_str(&format!("# InstructCanvas: {}\n\n", name));
    } else {
        output.push_str("# InstructCanvas Instructions\n\n");
    }

    for node_id in &order {
        if let Some(node) = doc.nodes.get(node_id) {
            output.push_str(&format!("## {}\n\n", node_id));
            match node.node_type {
                NodeType::Rule => {
                    if let Some(ref sev) = node.severity {
                        output.push_str(&format!("**Severity:** `{}`  \n", sev.as_str()));
                    }
                    if let Some(ref content) = node.content {
                        output.push_str(&format!("{}\n\n", content));
                    }
                }
                NodeType::Blocklist => {
                    if let Some(ref trigger) = node.trigger_on {
                        output.push_str(&format!("**Trigger:** `{}`  \n", trigger.as_str()));
                    }
                    if let Some(ref content) = node.content {
                        output.push_str(&format!("**Forbidden:** {}\n\n", content));
                    }
                }
                NodeType::Allowlist => {
                    if let Some(ref trigger) = node.trigger_on {
                        output.push_str(&format!("**Trigger:** `{}`  \n", trigger.as_str()));
                    }
                    if let Some(ref content) = node.content {
                        output.push_str(&format!("**Allowed:** {}\n\n", content));
                    }
                }
                NodeType::Condition => {
                    if let Some(ref cond) = node.condition {
                        output.push_str(&format!(
                            "If `{}` {} `{}`, then apply **{}**",
                            cond.variable, cond.operator, cond.value, cond.then_node
                        ));
                        if let Some(ref else_node) = cond.else_node {
                            output.push_str(&format!(", otherwise apply **{}**", else_node));
                        }
                        output.push_str("\n\n");
                    }
                }
                NodeType::Action => {
                    if let Some(ref content) = node.content {
                        output.push_str(&format!("{}\n\n", content));
                    }
                }
            }
        }
    }

    output.push_str("---\n_Generated by InstructCanvas (merged)_\n");
    Ok(output)
}
